_target_: torch.nn.Sequential
_args_:
  - _target_: modules.fx.Peak
    sr: ${sr}
    freq: 800
    min_freq: 33
    max_freq: 5400
  - _target_: modules.fx.Peak
    sr: ${sr}
    freq: 4000
    min_freq: 200
    max_freq: 17500
  - _target_: modules.fx.LowShelf
    sr: ${sr}
    freq: 115
    min_freq: 30
    max_freq: 200
  - _target_: modules.fx.HighShelf
    sr: ${sr}
    freq: 6000
    min_freq: 750
    max_freq: 8300
  - _target_: modules.fx.LowPass
    sr: ${sr}
    freq: 17500
    min_freq: 200
    max_freq: 18000
  - _target_: modules.fx.HighPass
    sr: ${sr}
    freq: 200
    min_freq: 16
    max_freq: 5300
  - _target_: modules.fx.CompressorExpander
    sr: ${sr}
    cmp_ratio: 2.0
    exp_ratio: 0.5
    at_ms: 50.0
    rt_ms: 50.0
    avg_coef: 0.3
    cmp_th: -18.0
    exp_th: -48.0
    make_up: 0.0
    lookahead: true
    max_lookahead: 15
  - _target_: modules.fx.SendFXsAndSum
    _args_:     
    # - _target_: modules.fx.FSDelay
    - _target_: modules.fx.FSSurrogateDelay
      sr: ${sr}
      delay: 400
      recursive_eq: true
      ir_duration: 8
      straight_through: true
      eq:
        _target_: modules.fx.LowPass
        sr: ${sr}
        freq: 8000
        min_freq: 200
        max_freq: 16000
        min_Q: 0.5
        max_Q: 1
    - _target_: modules.fx.FDN
      sr: ${sr}
      delays:
      - 997
      - 1153
      - 1327
      - 1559
      - 1801
      - 2099
      num_decay_freq: 49
      delay_independent_decay: true
      ir_duration: 12
      eq:
        _target_: torch.nn.Sequential
        _args_:
        - _target_: modules.fx.Peak
          sr: ${sr}
          freq: 800
          min_freq: 200
          max_freq: 2500
          min_Q: 0.1
          max_Q: 3
        - _target_: modules.fx.Peak
          sr: ${sr}
          freq: 4000
          min_freq: 600
          max_freq: 7000
          min_Q: 0.1
          max_Q: 3
        - _target_: modules.fx.LowShelf
          sr: ${sr}
          freq: 115
          min_freq: 30
          max_freq: 450
        - _target_: modules.fx.HighShelf
          sr: ${sr}
          freq: 8000
          min_freq: 1500
          max_freq: 16000
    cross_send: true
    pan_direct: true
